--------------------------------------------------------
--  File created - Tuesday-December-11-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACCOUNT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."ACCOUNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ADMIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."ADMIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEPT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."DEPT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOLD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."FOLD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOLLOW_UP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."FOLLOW_UP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INBOX_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."INBOX_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OUTBOX_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."OUTBOX_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "HR"."ACCOUNT" 
   (	"ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(80 BYTE), 
	"FULLNAME" VARCHAR2(100 BYTE), 
	"CREATED_UPDATED_AT" TIMESTAMP (6), 
	"LAST_LOGIN" TIMESTAMP (6), 
	"IP_ADDRESS" VARCHAR2(20 BYTE), 
	"RANK" VARCHAR2(20 BYTE), 
	"DEPT_ID" NUMBER(*,0), 
	"ROLE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "HR"."ADMIN" 
   (	"ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"FULLNAME" VARCHAR2(100 BYTE), 
	"CREATED_UPDATED_AT" TIMESTAMP (6), 
	"LAST_LOGIN" TIMESTAMP (6), 
	"IP_ADDRESS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "HR"."DEPT" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(60 BYTE), 
	"CREATED_UPDATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXPEDITED
--------------------------------------------------------

  CREATE TABLE "HR"."EXPEDITED" 
   (	"ID" NUMBER(*,0), 
	"DATE_RECEIVED" DATE, 
	"DATE_ADDED" TIMESTAMP (6), 
	"STATE" NUMBER(*,0), 
	"TOPIC" LONG, 
	"PATH" VARCHAR2(400 BYTE), 
	"ASSIGNED_FOLDER" VARCHAR2(100 BYTE), 
	"ARCH_NUM" NUMBER(*,0), 
	"ASSOCIATED_ID" NUMBER(*,0), 
	"RECORD_NUMBER" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOLDER
--------------------------------------------------------

  CREATE TABLE "HR"."FOLDER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"FOLD_DATE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FOLLOW_UP
--------------------------------------------------------

  CREATE TABLE "HR"."FOLLOW_UP" 
   (	"ID" NUMBER(*,0), 
	"ASSIGNED_OFFICER" NUMBER(*,0), 
	"STATE" NUMBER(*,0), 
	"TOPIC" LONG, 
	"PATH" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INBOX
--------------------------------------------------------

  CREATE TABLE "HR"."INBOX" 
   (	"ID" NUMBER(*,0), 
	"DATE_RECEIVED" DATE, 
	"DATE_ADDED" TIMESTAMP (6), 
	"STATE" NUMBER(*,0), 
	"TOPIC" LONG, 
	"PATH" VARCHAR2(400 BYTE), 
	"ASSIGNED_FOLDER" VARCHAR2(100 BYTE), 
	"ARCH_NUM" NUMBER(*,0), 
	"SENDER" VARCHAR2(100 BYTE), 
	"RECORD_NUMBER" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INBOX_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "HR"."INBOX_ATTACHMENT" 
   (	"ID" NUMBER(*,0), 
	"MSG_ID" NUMBER(*,0), 
	"PATH" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OUTBOX
--------------------------------------------------------

  CREATE TABLE "HR"."OUTBOX" 
   (	"ID" NUMBER(*,0), 
	"DATE_SENT" DATE, 
	"DATE_ADDED" TIMESTAMP (6), 
	"STATE" NUMBER(*,0), 
	"TOPIC" LONG, 
	"PATH" VARCHAR2(400 BYTE), 
	"ASSIGNED_FOLDER" VARCHAR2(100 BYTE), 
	"ARCH_NUM" NUMBER(*,0), 
	"RECEIVER" VARCHAR2(100 BYTE), 
	"RECORD_NUMBER" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OUTBOX_ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "HR"."OUTBOX_ATTACHMENT" 
   (	"ID" NUMBER(*,0), 
	"MSG_ID" NUMBER(*,0), 
	"PATH" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "HR"."REPLY" 
   (	"ID" NUMBER(*,0), 
	"DATE_SENT" DATE, 
	"DATE_ADDED" TIMESTAMP (6), 
	"STATE" NUMBER(*,0), 
	"TOPIC" LONG, 
	"PATH" VARCHAR2(400 BYTE), 
	"ASSIGNED_FOLDER" VARCHAR2(100 BYTE), 
	"ARCH_NUM" NUMBER(*,0), 
	"ASSOCIATED_ID" NUMBER(*,0), 
	"RECORD_NUMBER" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.ACCOUNT
SET DEFINE OFF;
REM INSERTING into HR.ADMIN
SET DEFINE OFF;
Insert into HR.ADMIN (ID,USERNAME,PASSWORD,FULLNAME,CREATED_UPDATED_AT,LAST_LOGIN,IP_ADDRESS) values (61,'ultim4t3','40bd001563085fc35165329ea1ff5c5ecbdbbeef','Giovanni Nabil',null,null,null);
REM INSERTING into HR.DEPT
SET DEFINE OFF;
REM INSERTING into HR.EXPEDITED
SET DEFINE OFF;
REM INSERTING into HR.FOLDER
SET DEFINE OFF;
REM INSERTING into HR.FOLLOW_UP
SET DEFINE OFF;
REM INSERTING into HR.INBOX
SET DEFINE OFF;
REM INSERTING into HR.INBOX_ATTACHMENT
SET DEFINE OFF;
REM INSERTING into HR.OUTBOX
SET DEFINE OFF;
REM INSERTING into HR.OUTBOX_ATTACHMENT
SET DEFINE OFF;
REM INSERTING into HR.REPLY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."ACCOUNT_PK" ON "HR"."ACCOUNT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCOUNT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."ACCOUNT_UK1" ON "HR"."ACCOUNT" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ATTACHMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."ATTACHMENT_PK" ON "HR"."INBOX_ATTACHMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."DEPT_PK" ON "HR"."DEPT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FOLDER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."FOLDER_PK" ON "HR"."FOLDER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FOLLOW_UP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."FOLLOW_UP_PK" ON "HR"."FOLLOW_UP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INBOX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."INBOX_PK" ON "HR"."INBOX" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MANAGER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MANAGER_PK" ON "HR"."ADMIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OUTBOX_ATTACHMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."OUTBOX_ATTACHMENT_PK" ON "HR"."OUTBOX_ATTACHMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OUTBOX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."OUTBOX_PK" ON "HR"."OUTBOX" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPLY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."REPLY_PK" ON "HR"."REPLY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index URGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."URGE_PK" ON "HR"."EXPEDITED" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ACCOUNT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."ACCOUNT_TRG" 
    before insert on HR.account
    for each row
begin
    select admin_seq.nextval
        into :new.ID
        from dual;
end;

/
ALTER TRIGGER "HR"."ACCOUNT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADMIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."ADMIN_TRG" 
    before insert on HR.admin
    for each row
begin
    select admin_seq.nextval
        into :new.ID
        from dual;
end;

/
ALTER TRIGGER "HR"."ADMIN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEPT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."DEPT_TRG" 
    before insert on HR.dept
    for each row
begin
    select admin_seq.nextval
        into :new.ID
        from dual;
end;

/
ALTER TRIGGER "HR"."DEPT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FOLD_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."FOLD_TRG" 
    before insert on HR.folder
    for each row
begin
    select fold_seq.nextval
        into :new.ID
        from dual;
end;  

/
ALTER TRIGGER "HR"."FOLD_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FOLLOW_UP_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."FOLLOW_UP_TRG" 
    before insert on HR.follow_up
    for each row
begin
    select admin_seq.nextval
        into :new.ID
        from dual;
end;

/
ALTER TRIGGER "HR"."FOLLOW_UP_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "HR"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_UK1" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."ACCOUNT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ACCOUNT" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ACCOUNT" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ACCOUNT" MODIFY ("FULLNAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ACCOUNT" MODIFY ("RANK" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ACCOUNT" MODIFY ("DEPT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ACCOUNT" MODIFY ("ROLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "HR"."ADMIN" ADD CONSTRAINT "MANAGER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."ADMIN" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ADMIN" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."ADMIN" MODIFY ("FULLNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "HR"."DEPT" ADD CONSTRAINT "DEPT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."DEPT" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."DEPT" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXPEDITED
--------------------------------------------------------

  ALTER TABLE "HR"."EXPEDITED" ADD CONSTRAINT "EXPEDITED_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."EXPEDITED" MODIFY ("ASSOCIATED_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXPEDITED" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXPEDITED" MODIFY ("DATE_RECEIVED" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXPEDITED" MODIFY ("TOPIC" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXPEDITED" MODIFY ("PATH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXPEDITED" MODIFY ("ASSIGNED_FOLDER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXPEDITED" MODIFY ("ARCH_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."EXPEDITED" MODIFY ("RECORD_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOLDER
--------------------------------------------------------

  ALTER TABLE "HR"."FOLDER" ADD CONSTRAINT "FOLDER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."FOLDER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FOLDER" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."FOLDER" MODIFY ("FOLD_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOLLOW_UP
--------------------------------------------------------

  ALTER TABLE "HR"."FOLLOW_UP" ADD CONSTRAINT "FOLLOW_UP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."FOLLOW_UP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INBOX
--------------------------------------------------------

  ALTER TABLE "HR"."INBOX" ADD CONSTRAINT "INBOX_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."INBOX" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."INBOX" MODIFY ("RECORD_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."INBOX" MODIFY ("DATE_RECEIVED" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."INBOX" MODIFY ("TOPIC" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."INBOX" MODIFY ("PATH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."INBOX" MODIFY ("ASSIGNED_FOLDER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."INBOX" MODIFY ("ARCH_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."INBOX" MODIFY ("SENDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INBOX_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "HR"."INBOX_ATTACHMENT" ADD CONSTRAINT "INBOX_ATTACHMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."INBOX_ATTACHMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OUTBOX
--------------------------------------------------------

  ALTER TABLE "HR"."OUTBOX" ADD CONSTRAINT "OUTBOX_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."OUTBOX" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."OUTBOX" MODIFY ("DATE_SENT" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."OUTBOX" MODIFY ("TOPIC" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."OUTBOX" MODIFY ("PATH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."OUTBOX" MODIFY ("ASSIGNED_FOLDER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."OUTBOX" MODIFY ("ARCH_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."OUTBOX" MODIFY ("RECEIVER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."OUTBOX" MODIFY ("RECORD_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "HR"."REPLY" ADD CONSTRAINT "REPLY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."REPLY" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."REPLY" MODIFY ("DATE_SENT" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."REPLY" MODIFY ("TOPIC" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."REPLY" MODIFY ("PATH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."REPLY" MODIFY ("ASSIGNED_FOLDER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."REPLY" MODIFY ("ARCH_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."REPLY" MODIFY ("ASSOCIATED_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."REPLY" MODIFY ("RECORD_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "HR"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_FK1" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "HR"."DEPT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXPEDITED
--------------------------------------------------------

  ALTER TABLE "HR"."EXPEDITED" ADD CONSTRAINT "EXPEDITED_FK1" FOREIGN KEY ("ASSOCIATED_ID")
	  REFERENCES "HR"."INBOX" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INBOX_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "HR"."INBOX_ATTACHMENT" ADD CONSTRAINT "INBOX_ATTACHMENT_FK1" FOREIGN KEY ("MSG_ID")
	  REFERENCES "HR"."INBOX" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "HR"."REPLY" ADD CONSTRAINT "REPLY_FK1" FOREIGN KEY ("ASSOCIATED_ID")
	  REFERENCES "HR"."INBOX" ("ID") ENABLE;
